export const PROMPT_CATEGORIES = [
  'Idea Validation',
  'Product Planning',
  'Base44 / Lovable Build Instructions',
  'UI and Design System',
  'Landing Page and Marketing Site',
  'User Onboarding',
  'Authentication and User Accounts',
  'Database and Data Model',
  'CRUD and Workflow',
  'AI Features',
  'Security',
  'QA and Testing',
  'Debugging',
  'Code Quality',
  'Performance',
  'SaaS Monetization',
  'Admin Panel',
  'Integrations',
  'SEO and Content',
  'Conversion and Growth',
  'Analytics',
  'Marketplace and Templates',
  'Client Services',
  'Compliance and Trust',
  'Specialized High-Value Prompts',
];